# Generated by Django 3.0 on 2019-12-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_title', models.CharField(max_length=100, verbose_name='Название предложения')),
                ('suggestion_author', models.CharField(default='None', max_length=12, verbose_name='Автор предложения')),
                ('suggestion_text', models.TextField(verbose_name='Текст предложения')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(default='None', max_length=12, verbose_name='Автор комментария')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Suggestion')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
