# Generated by Django 3.0 on 2019-12-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название предложения'),
        ),
    ]
