# Generated by Django 3.0 on 2019-12-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20191209_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_text',
            field=models.TextField(null=True, verbose_name='Текст предложения'),
        ),
    ]
