# Generated by Django 3.0 on 2019-12-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20191209_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=1000)),
                ('news_text', models.TextField(default='')),
                ('news_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
